### ISSUE TITLE
Not retrying even though step fails

### ISSUE THREAD

**Issue by oldergod** [nick-invision/retry#115]
I setup `retry` because of a flaky test which has never been a problem of timing out. It usually last 50~60 minutes and succeed or fail.

Here my config:
```yaml
      - name: Test
        uses: nick-fields/retry@v2
        with:
          max_attempts: 5
          timeout_minutes: 90
          shell: bash
          command: |
            ./gradlew -Pswift=false build --stacktrace --warning-mode all
```

Here is the job: https://github.com/square/wire/actions/runs/6036930069/job/16380190814
I cannot find log saying that anything has been retried and the step failed on the first attempt.

Why isn't it retrying? Is my config wrong?
