### ISSUE TITLE
Failure on error running a awscli command 

### ISSUE THREAD

**Issue by peterkline-es** [nick-invision/retry#12]
Probably completely related to Issue #4 but didn't want to jump on that "me too" since not sure if that ticket is just stale but also not sure if the actual issue is the command being run.  The `ec2 wait image-available` is a waiter command so not sure if what it does is throwing this off?  This command throws the events.js:187 immediately.

Error output
```js
Run nick-invision/retry@v1
  with:
    timeout_minutes: 1
    max_attempts: 25
    command: aws ec2 wait image-available --filters Name=name,Values=import-ami --profile automation
    retry_wait_seconds: 10
    polling_interval_seconds: 1
  env:
    AWS_PROFILE: automation
    AWS_REGION: us-east-1

events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn node ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn node',
  path: 'node',
  spawnargs: [
    '/data/actions-runner/_work/_actions/nick-invision/retry/v1/dist/exec.js',
    'aws ec2 wait image-available --filters Name=name,Values=import-ami --profile automation'
  ]
}
```

The command 
`aws ec2 wait image-available --filters Name=name,Values=import-ami --profile automation` 
works just fine with running within a normal `run` command but I need to retry this as AWS is completely random in how long it takes so I need the waiter to be run a few times before giving up.

Workflow call:
```yaml
# Commands within the retry action cannot be wrapped!
- name: Wait for New AMI Image to become available
uses: nick-invision/retry@v1
with:
  timeout_minutes: 1
  max_attempts: 25
  command: aws ec2 wait image-available --filters Name=name,Values=${{ env.IMPORT_IMAGE_ID }} --profile ${{ env.AWS_PROFILE }}
```
