### ISSUE TITLE
Feature Request: Support retrying uses: steps (actions) in addition to shell commands

### ISSUE THREAD

**Issue by xgboosted** [nick-invision/retry#155]
Currently, the `nick-fields/retry` action only supports retrying shell commands via the `run:` keyword. It does not support retrying `uses:` steps (i.e., other actions). This limitation means you cannot add retry logic to third-party actions or composite actions directly in your workflow.

__Feature request:__\
Add support for retrying `uses:` steps (actions), so that users can wrap any action (not just shell commands) with retry logic. This would allow for more robust workflows, especially when using actions that may intermittently fail due to network or external service issues.

__Example desired syntax:__

```yaml
- uses: nick-fields/retry@v3
  with:
    max_attempts: 3
    step:
      uses: some/action@v1
      with:
        foo: bar
```

This would make the action much more flexible and widely applicable in the GitHub Actions ecosystem.
