### ISSUE TITLE
Feature Request: Support retrying on multiple values, example: [error, timeout]

### ISSUE THREAD

**Issue by itsankit-google** [nick-invision/retry#156]
Currently, the `nick-fields/retry` action only supports retrying on error or timeout. This limitation means you cannot add retry on both error & timeout.

Feature request:
Add support for retrying using multiples type of failures.

Example desired syntax:

```
- name: Build Standalone
        uses: nick-fields/retry
        with:
          timeout_minutes: 60
          max_attempts: 3
          retry_on: [error, timeout]
```
