### ISSUE TITLE
Default shell, and option to select a different shell

### ISSUE THREAD

**Issue by drdanz** [nick-invision/retry#28]
It would be very useful, in order to convert easily a "normal" command if a `shell` parameter was supported, to change the shell executing the command.
See: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell

Also, from what I understand, on windows runners, the shell used is `cmd`, since the only way I could find to set a comment was using `rem`.
The one used by default from normal actions is `bash`, I think it would be great if the action default was the same.

**Comment by nick-invision** [comment]
Thanks for the issue!  I'll have to do a little homework on this one, I think running a node `exec` process (which is what this action uses) with non-default shell specified can be finnicky.

Can you give me a basic sample command that fails on the GitHub hosted Windows runner? If so, I can use that to further troubleshoot this.

**Comment by drdanz** [comment]
Sorry, I just double checked, I was wrong, the default on windows is `powershell`, not bash.

Here is the simplest example I could imagine

```yml
    - name: Ok
      if: runner.os == 'Windows'
      run: Get-ComputerInfo

    - name: Not ok
      if: runner.os == 'Windows'
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 10
        retry_wait_seconds: 1
        max_attempts: 3
        command: Get-ComputerInfo
```

**Comment by isaacrlevin** [comment]
Any update on this? Would love to control what shell gets ran

**Comment by isaacrlevin** [comment]
FYI @drdanz @nick-invision 
https://github.com/nick-invision/retry/pull/30

**Comment by isaacrlevin** [comment]
This can be closed

**Comment by nick-invision** [comment]
Thanks to the contribution of @isaacrlevin, an alternate shell can now be specified with this action.  Example:

``` yaml
uses: nick-invision/retry@v2
with:
  timeout_minutes: 10
  max_attempts: 3
  # if shell omitted, defaults to powershell on windows, bash otherwise.  Supported shells are bash, python, pwsh, sh, cmd, and powershell
  shell: pwsh
  command: dir
```
