### ISSUE TITLE
use

### ISSUE THREAD

**Issue by Leader755** [nick-invision/retry#34]
**Describe the bug**
A clear and concise description of what the bug is, **including the snippet from your workflow `yaml` showing your configuration and command being executed.**

**Expected behavior**

**Screenshots**

**Logs**
Enable [debug logging](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging#enabling-step-debug-logging) then attach the [raw logs](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs) (specifically the raw output of this action).

![image](https://user-images.githubusercontent.com/37180494/104889566-5bd59080-59a9-11eb-93bc-791c430b5937.png)
Can you continue to retry the failed step when it fails

**Comment by nick-invision** [comment]
Are you asking how to retry the `nick-invision/retry` action if it fails?  If so, yes, that is a feature of Actions (see [continue-on-error](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error) and [if](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsif)).

Or are you asking how to retry if the `on_retry_command` step fails? If so, that script output is [caught and ignored](https://github.com/nick-invision/retry/blob/7c68161adf97a48beb850a595b8784ec57a98cbb/src/index.ts#L109).

```
name: Do something with retries
uses: nick-invision/retry@v2
id: i-dont-know-why-you-would-do-this
continue-on-error: true
with:
  timeout_minutes: 10
  max_attempts: 3
  command: npm run some-typically-slow-script

name: Retry the retry
uses: nick-invision/retry@v2
if: steps.i-dont-know-why-you-would-do-this.outcome == 'success'
with:
  timeout_minutes: 10
  max_attempts: 3
  command: npm run some-typically-slow-script
```
