### ISSUE TITLE
Retry the whole action or job

### ISSUE THREAD

**Issue by TgSeed** [nick-invision/retry#52]
Hey,

I was wondering how can i retry the whole Action or the job on failure?

Let's assume i have this workflow:

```
name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}

```
How can i retry if `akhileshns/heroku-deploy` failed because of a timeout? is it even possible?

**Comment by nick-invision** [comment]
That is not possible with this Action, sorry.  

It's janky, but one thing you could do is just hardcode a retry step after the flaky step.  Something like:

```yaml
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
      - name: Rerun on failure 
        uses: akhileshns/heroku-deploy@v3.12.12
        if: ${{ failure()}}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
```
